-- phpMyAdmin SQL Dump
-- version 4.8.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 01, 2019 at 04:15 PM
-- Server version: 10.1.34-MariaDB
-- PHP Version: 5.6.37

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mysql`
--

-- --------------------------------------------------------

--
-- Table structure for table `krishnakatha`
--

CREATE TABLE `krishnakatha` (
  `ID` int(10) NOT NULL,
  `Title` varchar(100) NOT NULL,
  `Image` varchar(100) NOT NULL,
  `Description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `krishnakatha`
--

INSERT INTO `krishnakatha` (`ID`, `Title`, `Image`, `Description`) VALUES
(1, 'Krishna', '2017-05-20--10_01_04.jpg', 'Jai Shri Krishna'),
(3, 'Krishna learning to walk', 'krishnatrytowalking.jpg', 'Krishna tried to stand up and take a few steps on His own.\r\nFalling on His bottom, He would look unhappily at mother Yasoda and cry for a moment.\r\nTo encourage Him, mother Yasoda held Krishna\'s finger and walked beside Him.\r\nThen that lotus face, which had previously wilted from crying, blossomed with bright smile.\r\nMother Yasoda was in ecstasy looking at that smile.\r\nThus Krishna brought great joy to mother Yasoda with His moonlike face which bathed His body in the nectar of gentle beauty.\r\n( From the group pastime meditations )\r\nHare Krishna, Hare Krishna, Krishna Krishna, Hare Hare\r\nHare Rama, Hare Rama, Rama Rama, Hare Hare.\r\nPS: I humbly request all the devotees to please forward and share this moral/instructive stories they hear so that everyone can be benefited by hearing about Krishna and his dear devotees.\r\n'),
(4, 'Krishna following request of Gopis', 'krishnagopi.jpg', 'One day Radharani\'s grandmother Mukhara played a joke on Krishna by asking, \"O darling! Go fetch the large clay pot, the low wooden seat, and the drinking cup.\"\r\nWith a mild smile on His face, Krishna gingerly put some of the articles in His hands while balancing the remainder on His gorgeous belly.\r\nAfter walking some distance Krishna rested a little, and then slowly lifted those articles and brought them all to Mukhara.\r\nThe heavy items that He could not lift, He just touched and left alone.\r\nThen the wives of Upananda and Sunanda arrived and asked Vrajara Nanda if they could see Krishna.\r\nDue to having previously worshiped great devotees like Narada Muni and others, the wives of Upananda and Sunanda achieved the rare fortune of seeing the charming lotus feet of Krishna.\r\nThey lifted Krishna onto their laps and said, \"O darling! You are the son of the king, so just drop these things. Such work is not proper for You.\"\r\nThen they rebuked Mukhara and threw away the things Krishna had carried.\r\nIn so many ways the village ladies joked with Krishna.\r\nOne elderly gopi said, \"O my beloved Krishna! If You dance for me, I will give You some sweet butter.\"\r\nKrishna danced with delight for the pleasure of Yasoda and the gopis by gracefully moving His legs and gesturing artfully with His hands.\r\nAt another time, one gopi smiled and said, \"What is that darling, that looks like a golden doll? Isn\'t beautiful golden line adorning Your chest Your wife?\"\r\nEveryone laughed when Krishna agreed by smiling and slightly moving His head from side to side.\r\n'),
(5, 'Krishna is not bothered by the language.', 'krishnakatha (3).jpg', 'Once one person went to Vrindavana dhama to take darshan.\r\nOn his way back, after darshan, he saw one sadhu sitting outside his hut.\r\nHe was singing, \"ho, nayana hamare atake Shri Bihariji ke charano me.\" (My eyes are stuck in the lotus feet of Sri Krishna).\r\nHe was just repeating these line again and again. The voice of the sadhu and the tune were mesmerizing and the person got attracted to it and he sat next to the sadhu to listen.\r\nAfter some time he also joined the sadhu and started singing with him. After spending a long time there he started going home while singing the same line. He was in bliss.\r\nBy the time he reached home he somehow forgot the exact line. He just could not remember. He started singing the other way round :ho Bihariji ke nayan hamare charan kamal me atake.\"(Sri Krishna\'s eyes are stuck in my lotus feet!).\r\nSince he remembered the tune he kept singing the wrong line.\r\nWhen he sang it eleven times he was astonished to see Krishna standing in front of him. He fell at His feet.\r\nKrishna said, \"I have seen so many wonderful devotees but no one to beat you! My devotees say that their eyes get stuck in My lotus feet but you made My eyes got stuck in your lotus feet. So how could I not come to give darshan?\"\r\nHe became a devotee and spent his whole life singing Krishna\'s glory.\r\nNote: This proves that Krishna is not bothered about the words or language. He is just looking for our feelings of love.\r\n( From the group pastime meditations )\r\nHare Krishna, Hare Krishna, Krishna Krishna, Hare Hare\r\nHare Rama, Hare Rama, Rama Rama, Hare Hare.\r\n'),
(6, 'Wound on Radharani\'s foot', 'wound the feet.jpg', 'One day the Gopis saw a wound on Radharani\'s foot.\r\nGopis were worried to see that and they asked,\"How did it happen? When did you get it? Let\'s apply some cream on it.\"\r\nRadharani said, \"Oh it\'s nothing. This is a small old wound!\"\r\nGopis, \"It doesn\'t look old. We are sure its new one.\"\r\nRadharani, \"Once I snatched the flute from Shyamasundar. He ran after me and in the strife, His toenail scrapped the skin.\"\r\nGopis said: Shymasundar has left Vrindavana long back. So how come the wound is so fresh?\"\r\nRadharani said, \"Wound is old but I make it fresh. Whenever it\'s about to heal I just scrap the skin and make it fresh. This is the memento given by my Shyamasundar. When I see it the pain takes me back to all the wonderful pastimes that He performed. This makes me remember Him more and more. Please do not treat it. I wish it never dries.\"\r\nWhile speaking tears start flowing from Her eyes. Her love is in separation and tells a lot about Their eternal love!\r\nSrimati Radharani ki jaya!\r\n( From the group pastime meditations )\r\nHare Krishna, Hare Krishna, Krishna Krishna, Hare Hare\r\nHare Rama, Hare Rama, Rama Rama, Hare Hare.\r\nPS: I humbly request all the devotees to please forward and share this moral/ instructive stories they hear so that everyone can be benefited by hearing about Krishna and his dear devotees.\r\n'),
(7, 'Krishna gives an amazing reply to mother Yashoda', 'full_size_20160730173612.jpg', 'Once mother Yashoda was offering ghee lamps to Yamuna, she notished that no lamps was moving with the flow, then she saw Krishna taking out the lamps with the stick.  She asked Krishna what he was doing? kanha said he was saving the lamps from drowing.  She started laughing and said, \"there are so many lamps, how many you will save?\"  Krishna gave a very remarkable reply.  He said, \"I have not tacken any contract to save all. those who come near me i will save them.\"  SO IF YOU WANT SAVE YOURSELF JUST SURRENDER TO KRISHNA...'),
(8, 'The poor man and gentalman', 'full_size_20160728080050.jpg', 'There was a person who was very merciful and a through gentelman. One day one very poor person approached him and said, \"Sir please lend me your field. i will produce graines and make some mony for myself.\"   The gentelman gave him his fields and on top of this he have five laobors to help him so that he can produce more grains.   The poor man was very happy because he got the land some laobor assistanc too. But he got lost in his thoughts of having a field. The laobors too were working acording to their own whims. When the time came for taking account of the produce.  Since every aspect was neglected. No proper care, no proper seeds, and no proper water.    When the gentalman asked him to give back his land the poor man started crying. He said! \"I am sorry, i was lost in happiness of getting the land and neglected my duty. I did not even use the five laobors properly.   Here is the revealation - The gentalman is none other than Krishna.  The poor man each of \"us\".   The field is our body.  The five laobors are the five sense organs - eyes, eaes,  nose, tounge, and the mind.  Krishna has given us this body. We have to keep our sense in control and perform our prescribed duty. Otherwise we too have to cry like that poor man.'),
(9, 'Jai Shri Krishna', '1200-481253425-light-pink-lotus-flower.jpg', 'Hare Krishna Hare Krishna Krishna Krishna Hare Hare\r\nHare Rama Hare Rama Rama Rama Hare Hare...'),
(1, 'Krishna', '2017-05-20--10_01_04.jpg', 'Jai Shri Krishna'),
(3, 'Krishna learning to walk', 'krishnatrytowalking.jpg', 'Krishna tried to stand up and take a few steps on His own.\r\nFalling on His bottom, He would look unhappily at mother Yasoda and cry for a moment.\r\nTo encourage Him, mother Yasoda held Krishna\'s finger and walked beside Him.\r\nThen that lotus face, which had previously wilted from crying, blossomed with bright smile.\r\nMother Yasoda was in ecstasy looking at that smile.\r\nThus Krishna brought great joy to mother Yasoda with His moonlike face which bathed His body in the nectar of gentle beauty.\r\n( From the group pastime meditations )\r\nHare Krishna, Hare Krishna, Krishna Krishna, Hare Hare\r\nHare Rama, Hare Rama, Rama Rama, Hare Hare.\r\nPS: I humbly request all the devotees to please forward and share this moral/instructive stories they hear so that everyone can be benefited by hearing about Krishna and his dear devotees.\r\n'),
(4, 'Krishna following request of Gopis', 'krishnagopi.jpg', 'One day Radharani\'s grandmother Mukhara played a joke on Krishna by asking, \"O darling! Go fetch the large clay pot, the low wooden seat, and the drinking cup.\"\r\nWith a mild smile on His face, Krishna gingerly put some of the articles in His hands while balancing the remainder on His gorgeous belly.\r\nAfter walking some distance Krishna rested a little, and then slowly lifted those articles and brought them all to Mukhara.\r\nThe heavy items that He could not lift, He just touched and left alone.\r\nThen the wives of Upananda and Sunanda arrived and asked Vrajara Nanda if they could see Krishna.\r\nDue to having previously worshiped great devotees like Narada Muni and others, the wives of Upananda and Sunanda achieved the rare fortune of seeing the charming lotus feet of Krishna.\r\nThey lifted Krishna onto their laps and said, \"O darling! You are the son of the king, so just drop these things. Such work is not proper for You.\"\r\nThen they rebuked Mukhara and threw away the things Krishna had carried.\r\nIn so many ways the village ladies joked with Krishna.\r\nOne elderly gopi said, \"O my beloved Krishna! If You dance for me, I will give You some sweet butter.\"\r\nKrishna danced with delight for the pleasure of Yasoda and the gopis by gracefully moving His legs and gesturing artfully with His hands.\r\nAt another time, one gopi smiled and said, \"What is that darling, that looks like a golden doll? Isn\'t beautiful golden line adorning Your chest Your wife?\"\r\nEveryone laughed when Krishna agreed by smiling and slightly moving His head from side to side.\r\n'),
(5, 'Krishna is not bothered by the language.', 'krishnakatha (3).jpg', 'Once one person went to Vrindavana dhama to take darshan.\r\nOn his way back, after darshan, he saw one sadhu sitting outside his hut.\r\nHe was singing, \"ho, nayana hamare atake Shri Bihariji ke charano me.\" (My eyes are stuck in the lotus feet of Sri Krishna).\r\nHe was just repeating these line again and again. The voice of the sadhu and the tune were mesmerizing and the person got attracted to it and he sat next to the sadhu to listen.\r\nAfter some time he also joined the sadhu and started singing with him. After spending a long time there he started going home while singing the same line. He was in bliss.\r\nBy the time he reached home he somehow forgot the exact line. He just could not remember. He started singing the other way round :ho Bihariji ke nayan hamare charan kamal me atake.\"(Sri Krishna\'s eyes are stuck in my lotus feet!).\r\nSince he remembered the tune he kept singing the wrong line.\r\nWhen he sang it eleven times he was astonished to see Krishna standing in front of him. He fell at His feet.\r\nKrishna said, \"I have seen so many wonderful devotees but no one to beat you! My devotees say that their eyes get stuck in My lotus feet but you made My eyes got stuck in your lotus feet. So how could I not come to give darshan?\"\r\nHe became a devotee and spent his whole life singing Krishna\'s glory.\r\nNote: This proves that Krishna is not bothered about the words or language. He is just looking for our feelings of love.\r\n( From the group pastime meditations )\r\nHare Krishna, Hare Krishna, Krishna Krishna, Hare Hare\r\nHare Rama, Hare Rama, Rama Rama, Hare Hare.\r\n'),
(6, 'Wound on Radharani\'s foot', 'wound the feet.jpg', 'One day the Gopis saw a wound on Radharani\'s foot.\r\nGopis were worried to see that and they asked,\"How did it happen? When did you get it? Let\'s apply some cream on it.\"\r\nRadharani said, \"Oh it\'s nothing. This is a small old wound!\"\r\nGopis, \"It doesn\'t look old. We are sure its new one.\"\r\nRadharani, \"Once I snatched the flute from Shyamasundar. He ran after me and in the strife, His toenail scrapped the skin.\"\r\nGopis said: Shymasundar has left Vrindavana long back. So how come the wound is so fresh?\"\r\nRadharani said, \"Wound is old but I make it fresh. Whenever it\'s about to heal I just scrap the skin and make it fresh. This is the memento given by my Shyamasundar. When I see it the pain takes me back to all the wonderful pastimes that He performed. This makes me remember Him more and more. Please do not treat it. I wish it never dries.\"\r\nWhile speaking tears start flowing from Her eyes. Her love is in separation and tells a lot about Their eternal love!\r\nSrimati Radharani ki jaya!\r\n( From the group pastime meditations )\r\nHare Krishna, Hare Krishna, Krishna Krishna, Hare Hare\r\nHare Rama, Hare Rama, Rama Rama, Hare Hare.\r\nPS: I humbly request all the devotees to please forward and share this moral/ instructive stories they hear so that everyone can be benefited by hearing about Krishna and his dear devotees.\r\n'),
(7, 'Krishna gives an amazing reply to mother Yashoda', 'full_size_20160730173612.jpg', 'Once mother Yashoda was offering ghee lamps to Yamuna, she notished that no lamps was moving with the flow, then she saw Krishna taking out the lamps with the stick.  She asked Krishna what he was doing? kanha said he was saving the lamps from drowing.  She started laughing and said, \"there are so many lamps, how many you will save?\"  Krishna gave a very remarkable reply.  He said, \"I have not tacken any contract to save all. those who come near me i will save them.\"  SO IF YOU WANT SAVE YOURSELF JUST SURRENDER TO KRISHNA...'),
(8, 'The poor man and gentalman', 'full_size_20160728080050.jpg', 'There was a person who was very merciful and a through gentelman. One day one very poor person approached him and said, \"Sir please lend me your field. i will produce graines and make some mony for myself.\"   The gentelman gave him his fields and on top of this he have five laobors to help him so that he can produce more grains.   The poor man was very happy because he got the land some laobor assistanc too. But he got lost in his thoughts of having a field. The laobors too were working acording to their own whims. When the time came for taking account of the produce.  Since every aspect was neglected. No proper care, no proper seeds, and no proper water.    When the gentalman asked him to give back his land the poor man started crying. He said! \"I am sorry, i was lost in happiness of getting the land and neglected my duty. I did not even use the five laobors properly.   Here is the revealation - The gentalman is none other than Krishna.  The poor man each of \"us\".   The field is our body.  The five laobors are the five sense organs - eyes, eaes,  nose, tounge, and the mind.  Krishna has given us this body. We have to keep our sense in control and perform our prescribed duty. Otherwise we too have to cry like that poor man.'),
(9, 'Jai Shri Krishna', '1200-481253425-light-pink-lotus-flower.jpg', 'Hare Krishna Hare Krishna Krishna Krishna Hare Hare\r\nHare Rama Hare Rama Rama Rama Hare Hare...');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
